name: CI/CD pipeline Deploy Terraform Infrastructure

on:
  push:
    branches: [main]

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.PAT }}
          approvers: LucasCode812, LuukRaaijmakers, MaxvandeKerkhof, noarezaifontys, rverspaij, Youssefontys

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Terraform code
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6

      - name: Connect to server and Deploy Infrastructure
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_KEY }}
          script: |
            sudo su
            echo ${{ secrets.PAT }}
            cd /home/ubuntu
            sudo rm -rf *
            sudo git clone https://${{ secrets.PAT }}@github.com/LucasCode812/terraform.git
            cd /home/ubuntu/terraform
            sudo terraform init
            sudo terraform fmt
            sudo terraform apply -auto-approve
